
cache:
    directories:
        - '$HOME/.composer/cache'

matrix:
    fast_finish: true
    include:
        -
            sudo: false
            language: 'php'
            php: '5.6'
            env:
                - 'COMPOSER_NO_INTERACTION=1 COMPOSER_DISABLE_XDEBUG_WARN=1'
        -
            os: 'osx'
            language: 'generic'
            env:
                - 'COMPOSER_NO_INTERACTION=1 COMPOSER_DISABLE_XDEBUG_WARN=1 _PHP=php70 '

before_install:
    - 'src-dev/scripts/travis/before_install.sh'

install:
    - 'composer install --no-interaction'

script:
    - './bin/robo --ansi lint'
    - './bin/robo --ansi test'

after_success:
    - 'bash <(curl -s https://codecov.io/bash)'

notifications:
    email: false
